# Generated by Django 5.1.1 on 2024-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('margherita', 'Margherita'), ('pepperoni', 'Pepperoni'), ('vegetarian', 'Vegetarian'), ('hawaiian', 'Hawaiian')], max_length=20)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
